version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 9.2.2
  - dependency-name: mocha
    versions:
    - 8.2.1
